### ISSUE TITLE
Missing Reviews in Search Results?

### ISSUE THREAD

**Issue by KevinJacob** [Yelp/yelp-ios#40]
When I'm trying to load the reviews for a business it shows a "reviewCount" greater than 0 but the array of reviews has 0 objects. This is with all businesses I have attempted to view and I've confirmed that all of them did have reviews online. 

![screen shot 2016-07-17 at 05 34 54](https://cloud.githubusercontent.com/assets/3739136/16899878/cecd8b32-4be0-11e6-9184-faf33e7ef582.png)

**Comment by mittonk** [comment]
1. On the API level: Review text is returned from the more detailed Business endpoint:
https://www.yelp.com/developers/documentation/v2/business

The Search endpoint includes a short `snippet_text`, suitable for a search-results summary:
https://www.yelp.com/developers/documentation/v2/search_api

Once you've found businesses you like, use the Business endpoint to get more details about them.

2. On the clientlib level:
It's confusing (and I'd say a bug) to show the `reviews` key in Search response objects, since it will never be filled.  @d9chen , thoughts?

**Comment by KevinJacob** [comment]
Alright that makes sense. You're right though, it would be nice to see some kind of indication that that key wouldn't be populated. Thanks for clarifying.

**Comment by SSheldon** [comment]
After the update for the new v3 API (#43) there are no more reviews on the business object at all, they come from a separate endpoint :) Closing this out!
