### ISSUE TITLE
Yelp API v3

### ISSUE THREAD

**Issue by davecom** [Yelp/yelp-ios#43]
Are there plans to migrate this library to V3 of the Yelp API? If so, what is the timeline like? Thanks!

**Comment by mittonk** [comment]
We're figuring out the clientlib strategy for V3, no firm timeline yet.

**Comment by SSheldon** [comment]
Some suggestions on how we might want to go about this:
* Not a ton of great OAuth2 libraries, our best bet looks like [NXOAuth2Client](https://github.com/nxtbgthng/OAuth2Client). Its code looks a little old, but it has lots of users.
* Instead of a public init method, YLPClient will probably need an asynchronous factory method, since creating a client involves a network request to authenticate.
* The authentication type that the v3 API uses is performed in NXOAuth2Client via `-[NXOAuth2AccountStore requestClientCredentialsAccessWithType:]`
* NXOAuth2 uses NSURLConnection :( but we can maybe use it for just signing and still make the requests ourselves? There's an `-[NXOAuth2Request signedURLRequest]` method for getting a signed request.

**Comment by SSheldon** [comment]
Okay, with #47, #48, #50, and #51 merged this library is fully working on the new API.

I've found one bug, ticketed in #52, that I'd like to fix before publishing the new version and closing this out.

**Comment by SSheldon** [comment]
The update is done! A new major version of this library, 2.0, was published.

It doesn't yet include all the functionality of the v3 API, but it supports all functionality that was in v2 for which there's a v3 parallel. We can add the new functionality in followups, I'll close this issue out.
